/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddWorkout: typeof import('./src/components/addWorkout.vue')['default']
    EmailLogin: typeof import('./src/components/emailLogin.vue')['default']
    FormLogin: typeof import('./src/components/formLogin.vue')['default']
    FormSignup: typeof import('./src/components/formSignup.vue')['default']
    GoogleAuth: typeof import('./src/components/googleAuth.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LogIn: typeof import('./src/components/logIn.vue')['default']
    MyWorkouts: typeof import('./src/components/myWorkouts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
